# code: language: jinja-yaml
{% set name = "prometheus-cpp" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/jupp0r/prometheus-cpp/releases/download/v{{ version }}/prometheus-cpp-with-submodules.tar.gz
    sha256: 0d6852291063c35853e88805c73b52f73c0c08b78c1e7bc4d588fcf72a7172eb

build:
  number: 1
  always_include_files:
    - lib/cmake/prometheus-cpp/           # [unix]
    - Library/lib/cmake/prometheus-cpp/   # [win]
  run_exports:
    - {{ pin_subpackage('prometheus-cpp', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - ninja

    # For cross-compiling
    - libcurl                 # [build_platform != target_platform]
    - curl                    # [build_platform != target_platform]
    - zlib                    # [build_platform != target_platform]
  host:
    - libcurl
    - zlib
  run:
    - zlib
    - libcurl

test:
  commands:
    - test -d $PREFIX/include/prometheus/                                   # [unix]
    - test -d $PREFIX/lib/cmake/prometheus-cpp/                             # [unix]
    - test -f $PREFIX/lib/cmake/prometheus-cpp/prometheus-cpp-config.cmake  # [unix]
    - test -f "${PREFIX}/lib/libprometheus-cpp-core${SHLIB_EXT}"           # [unix]
    - test -f "${PREFIX}/lib/libprometheus-cpp-pull${SHLIB_EXT}"           # [unix]
    - test -f "${PREFIX}/lib/libprometheus-cpp-push${SHLIB_EXT}"           # [unix]
    - if not exist %LIBRARY_INC%\prometheus exit 1                                        # [win]
    - if not exist %LIBRARY_LIB%\cmake\prometheus-cpp exit 1                              # [win]
    - if not exist %LIBRARY_LIB%\cmake\prometheus-cpp\prometheus-cpp-config.cmake exit 1  # [win]
    - dir %LIBRARY_LIB%\prometheus-*.lib                                                  # [win]
    - if not exist %LIBRARY_LIB%\prometheus-cpp-core.lib exit 1                           # [win]
    - if not exist %LIBRARY_LIB%\prometheus-cpp-pull.lib exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\prometheus-cpp-push.lib exit 1                      # [win]

about:
  home: https://github.com/jupp0r/prometheus-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prometheus Client Library for Modern C++
  description: |
    This library aims to enable Metrics-Driven Development for C++ services. It implements the
    Prometheus Data Model, a powerful abstraction on which to collect and expose metrics. We
    offer the possibility for metrics to be collected by Prometheus, but other push/pull collections
    can be added as plugins.
  dev_url: https://github.com/jupp0r/prometheus-cpp

extra:
  recipe-maintainers:
    - lidavidm
    - mariusvniekerk
